mainSections = ["docs"]

[sidebar]
emoji = "😜"
subtitle = "where logic meets creativity"

[sidebar.avatar]
local = true
enabled = true
src = "img/avatar.webp"

[article]
math = false
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

[footer]
since = 2025
customText = ""

[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[comments]
enabled = false
