baseURL: "https://blog.ggymm.xyz"
title: Blog
theme: ["paper"]
mainsections: ["docs"]
pagination:
  pagerSize: 5

summaryLength: "0" 
hasCJKLanguage: true
defaultContentLanguage: "zh-cn"

params:
  env: production
  ShowPageNums: true

  homeInfoParams:
    Title: "GGYMM's Blog"
    Content: "Welcome to follow me on [GitHub](https://github.com/ggymm)"

outputs:
  home:
    - HTML

languages:
  zh-cn:
    menu:
      main:
        - name: 标签
          url: tags/
          weight: 1
        - name: 归档
          url: archives/
          weight: 2
        - name: 搜索
          url: search/
          weight: 3